debug: false
uuid: 06558224-5d8e-4107-a623-22d3c4f39147
token_id: 0AeRSFDgMDlLdVRk
token: ueFNUpcUJWN41Kr7axKitxzUOAEuzJieYfSAZoJ1qgyPKTPA6D6MPu3EvkviHQOt
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/165.22.248.163/fullchain.pem
    key: /etc/letsencrypt/live/165.22.248.163/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
