debug: false
uuid: f9a7f87c-6605-4929-8297-1607941870f9
token_id: 2x0hcwnlE4ntOJ0p
token: dD5XKco2DIK1CyZtj9jKjDXmkiJBp3SkxUgvI9NqroqR4xZkZdelAwayoVWmbFbG
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/152.42.236.145/fullchain.pem
    key: /etc/letsencrypt/live/152.42.236.145/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
