debug: false
uuid: 96763f6f-0d5d-46fc-a7a2-533adcb1e64e
token_id: mDlrTa1ISJPgGBil
token: N8aCl9ABLCSfe1oVPZnQdt1v1U9P7f3o64MSAxQwdTxwCemKO0N8TX4bUxS5jdFp
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/157.230.246.127/fullchain.pem
    key: /etc/letsencrypt/live/157.230.246.127/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
