debug: false
uuid: 172f43c5-abe9-44d1-8b23-994d2c98e006
token_id: VmLx7UO6P6dUouRE
token: 1u5NI2oaaojWDIxIX8c8Q9gA9qOEUGiqBbqtaUTY5Mscm2KhOICGLjdeHM6VLP3j
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/159.223.87.192/fullchain.pem
    key: /etc/letsencrypt/live/159.223.87.192/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
