debug: false
uuid: 02ef37ec-be8d-4d99-961f-627052d13782
token_id: vbPRe5Pu7iDjoNrj
token: vPvZERvz3nD46dObVifImLNTAGyk6TK1ERDvS3HRoF6t6BB8Jc2fNmTarF5BO5ft
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/165.232.175.52/fullchain.pem
    key: /etc/letsencrypt/live/165.232.175.52/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
