debug: false
uuid: 1766e904-19d6-47b7-aab5-d498deb89426
token_id: qo8D2o0lmcQEYY2g
token: Kxs7NTm99fSPn0Gbjx77jLr7puxu45CycObOiZoo7D4G7H48OL0U9LtGEV770sLn
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/68.183.228.29/fullchain.pem
    key: /etc/letsencrypt/live/68.183.228.29/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
