debug: false
uuid: 40d1c33b-2df8-45c8-88de-6752a1c13c5f
token_id: dyuxwBPWgRFurTtU
token: M1yun5SqoQInKSLUSNjIqdA5XYrQgWNMPeSawWonBM04MiKMz8w56ZOzsHn2FVCU
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/209.97.160.245/fullchain.pem
    key: /etc/letsencrypt/live/209.97.160.245/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
