debug: false
uuid: 9756c5fe-8d1a-445e-8284-92f937459471
token_id: 03NDLLpSymfylJ7a
token: 9l1CZor09LI8FcuHxPZRdNojYW4b5f0Ph1KOFAowhKss3JNHqOZuKSvirXSh0vQD
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/174.138.19.240/fullchain.pem
    key: /etc/letsencrypt/live/174.138.19.240/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
