debug: false
uuid: 2939a0c0-145f-4a21-acaa-f9d47ed6ad0d
token_id: 0BZRYeN5Zu5OKm1Z
token: oVfONzYh25NxOBs6zRNzVZtXRVUPQewrJIEOHr0rACF4Dd0VG44xsUeqhbr3fE5o
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/178.128.117.222/fullchain.pem
    key: /etc/letsencrypt/live/178.128.117.222/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
