
debug: false
uuid: 638cc646-9a72-49af-a2ae-c0101af18f4a
token_id: 2zr3QiZU0e7mtlwJ
token: 1cXpaJiGr8PbNGcHyY3KT7XrhbaA6ag4zWtvYKLreTVouiCwSJjYKRRS8FKaViPJ
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/128.199.98.115/fullchain.pem
    key: /etc/letsencrypt/live/128.199.98.115/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
