debug: false
uuid: 474b6e28-e601-4413-a2bc-e55316bd7bcc
token_id: 4rxCZlgnQrevPi0I
token: O8rySDa6zGb1tAtQws7ySo3zJSFMYMfbNbJP2tjVKsif8L3B3Znknv0CCVvEDy3w
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/159.223.88.12/fullchain.pem
    key: /etc/letsencrypt/live/159.223.88.12/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
