debug: false
uuid: c77c1fc2-707b-4f45-947d-6acf61afd5b3
token_id: N1h8vYMDvirUoUPP
token: KJX1JK4T6xPJNCtej30ynd9GKtinIzeRwfy1XzjfXuP8QN4bxFszz2aCxEEmhBRo
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/167.99.66.25/fullchain.pem
    key: /etc/letsencrypt/live/167.99.66.25/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
