debug: false
uuid: 8396f3a7-76ae-4b14-9159-d2a38efec250
token_id: JB30kn3yXBaalNUq
token: BIVvCbHXTYM5Jkk8YQImbDs3cXyqNqTcFouPADM2kEgTIOZcrTHIKnovsK44swZm
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/159.65.4.18/fullchain.pem
    key: /etc/letsencrypt/live/159.65.4.18/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
