debug: false
uuid: b72c8127-71eb-4d5d-92fc-9b3b7428437e
token_id: adqghSk6sUiL36ur
token: DJxykHZKOVqCuV4IQ05VT8yNqs0Ierm00zdcQVqewRRbeiNNQaaGUdhRY0nQ2OED
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/146.190.85.223/fullchain.pem
    key: /etc/letsencrypt/live/146.190.85.223/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
