#!/bin/bash
set -e

# --- Create coder user with sudo ---
adduser --gecos "" coder
usermod -aG sudo coder
printf "coder ALL=(ALL) NOPASSWD:ALL\n" >/etc/sudoers.d/90-coder-nopasswd
chmod 440 /etc/sudoers.d/90-coder-nopasswd

# --- SSH key for coder ---
mkdir -p /home/coder/.ssh
cp /root/.ssh/authorized_keys /home/coder/.ssh/ 2>/dev/null  true
chown -R coder:coder /home/coder/.ssh
chmod 700 /home/coder/.ssh
chmod 600 /home/coder/.ssh/authorized_keys
