debug: false
uuid: 5ec1e791-2f61-4974-9d0d-61e43b27d459
token_id: lS6j6gts9mpgz8B8
token: 67fVsEisvS8lNZSl7hSJSf1H74JGTJGmUNlH7gIRnLceiLnHfCkFCMFKcze1SRei
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/152.42.199.11/fullchain.pem
    key: /etc/letsencrypt/live/152.42.199.11/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
