debug: false
uuid: aa0f47ea-e8a8-4e3a-a19f-2ad69b5e286b
token_id: 8bRBnVM7A9BQktlx
token: riOy8ceCso3v0gsB7XGhVst0KNmEejM3TwPTV3TucVxa6PunS7NKLkB7Ju9zIw9S
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/206.189.149.220/fullchain.pem
    key: /etc/letsencrypt/live/206.189.149.220/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
