debug: false
uuid: cc3c03ae-e117-4e6d-86e1-624238ac87f1
token_id: 7sfWRRdeKAsZtL09
token: cx7gXK5C570t2LOBYoGoyV4dPdKnCA4fi9Yt9iJZudew4EW9GGggRc3fuFdIbUEB
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/152.42.238.168/fullchain.pem
    key: /etc/letsencrypt/live/152.42.238.168/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
