debug: false
uuid: 1c85ca98-5b85-4af5-b106-2ef6472e7e45
token_id: VH8qNdGb9egxZmQ5
token: gsXEXhhUInUO4Y0CR3C4HCCPHybdMhriKTRj82apgYLlHtVMvIcvMaa6metfzQeC
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/159.223.69.38/fullchain.pem
    key: /etc/letsencrypt/live/159.223.69.38/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
