debug: false
uuid: 00e60da6-514f-483d-be9f-9fe8fdb95bf9
token_id: tqY8JcrOdWjKZT2e
token: hgt2BsQHLiK3uOwXixooumCXFJndmmwcaSTy5Te2oW7wjb7mq7DnxxftneLPqJ2U
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/128.199.172.136/fullchain.pem
    key: /etc/letsencrypt/live/128.199.172.136/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
