debug: false
uuid: 299f7820-bf61-42ea-b76a-c29c0476d0e5
token_id: CUKMLEFJ0WF7iqgu
token: czeJzGO65YwaCbMuHSIuoJXNOMpyaPg2vzUDe55CjVySKxVBBMGjCy04UhSViRs0
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/146.190.85.116/fullchain.pem
    key: /etc/letsencrypt/live/146.190.85.116/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
