debug: false
uuid: d64fd9a3-67d1-41c1-bce0-37351d2e9e91
token_id: Evh47HpZncjWsLZG
token: 0YhPgMCAP78Hx3RPFHTIezKfbQYrfHA7CVrWC4y2stfe0R59wkE1gQSbjfepN3Di
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/146.190.88.183/fullchain.pem
    key: /etc/letsencrypt/live/146.190.88.183/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
