debug: false
uuid: b2d15ed1-9253-403a-b0ba-0e53f81b22f1
token_id: mCFcwHF4WnDODkeg
token: JngQYQriLhGFpAzKOyhzQcZeTiGQTnwW9ejlPsjCKl209KGcoWGZJbnWOI86SnE2
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/209.97.172.139/fullchain.pem
    key: /etc/letsencrypt/live/209.97.172.139/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
