debug: false
uuid: c9f117c7-19fc-4d49-8ce9-216b7e4173cc
token_id: Aam6U8PENmwgOjxS
token: 5kdCg7MYQWyaInCq9Y1EbijHrQxYnYh0QyqKIWT8U1kmLUcvOhL3WSKO5Z7B2Ene
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/167.172.69.77/fullchain.pem
    key: /etc/letsencrypt/live/167.172.69.77/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
