debug: false
uuid: 476c2fdd-1167-4f59-b2f7-4238f8782026
token_id: i3XkfAA1gAiVcwnz
token: fDqthfhApF7MRB01m5Gh4igCjKwRmOLaAoQlJkqAjyd2P8LeuTHoY2LVdB0zU099
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/167.172.93.164/fullchain.pem
    key: /etc/letsencrypt/live/167.172.93.164/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
