debug: false
uuid: 832802d7-298b-4e16-b565-0d5462d3f161
token_id: G3wmvhGlfvfmRjga
token: iOuyvDuNpn7GWyWZeLDoUKVT06bqXcERofzb7tsVEkAKgmljYFQc8njkioAs5xUx
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/128.199.210.81/fullchain.pem
    key: /etc/letsencrypt/live/128.199.210.81/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
