debug: false
uuid: 9688f2cd-88ae-4ebd-a22a-bb53a2ba9a07
token_id: ITlt0NlJZDxFrBGN
token: knLQW6JBhGALZSupUHlJxeQbqTHyC8VJppCgIc5xJXSmSm6Q0GWmUjS5f3aXIrEy
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/157.230.41.74/fullchain.pem
    key: /etc/letsencrypt/live/157.230.41.74/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
