debug: false
uuid: ac028db7-5641-4f99-b02e-3aa6ae19a8f0
token_id: 0sbArZghzitLGNPS
token: 8BbtdKP1yFPqoEY4W1364oFzPBhCKETXVdRvjyScLIeWROC63hgsBSulpTQKhY8p
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/143.198.221.25/fullchain.pem
    key: /etc/letsencrypt/live/143.198.221.25/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
