debug: false
uuid: 55f32887-2f54-49e8-bfdf-4e4243d1e5b0
token_id: HVdViHB8GLdhIA8o
token: LM6YbvKy4Px4R0iHDwAKLxOubCQfdPfn68w7w3JKsTAzTY9kDiha9kNgV1fZaiXP
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/139.59.227.253/fullchain.pem
    key: /etc/letsencrypt/live/139.59.227.253/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
