debug: false
uuid: b85a7afb-7d54-4b97-bdf2-bbde1d48dbc6
token_id: OSZ2TY2iNXEl6X2a
token: gZOQC2mlICbDp5NIveZPErLLgDnBNPWx0dM5YYk6zKUxuXGvFkC0rEwwqGb6lQ5X
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/146.190.107.3/fullchain.pem
    key: /etc/letsencrypt/live/146.190.107.3/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
