debug: false
uuid: 7916ee97-076e-4971-8678-1b0c278936de
token_id: b2KmMaoEmXhZAk3D
token: h2wFeK1N04dKAMSandmXqHyYlhYmT7eQdxaT2nvCp9ka0vyrggWiRQQnIoZBkPZk
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/143.198.93.74/fullchain.pem
    key: /etc/letsencrypt/live/143.198.93.74/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
