debug: false
uuid: a9f04f52-91a4-49ce-9c49-3ac6a378b45b
token_id: P0b083F6xoUqykb3
token: qXHVwiBZTeDCqeukRetjZk7Dz5ay6pL1KwdBh8JJtboNuyEB72uECj75VkumQnEQ
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/167.99.66.25/fullchain.pem
    key: /etc/letsencrypt/live/167.99.66.25/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
