debug: false
uuid: 7e8d1602-cfb9-493f-b8f0-855f12cfa9d6
token_id: v0bfkfsn2FroA6WY
token: m8NueWQ0WMM21fSJRyrsJjOTy5rh92FTL9UWNELhIj3cdr9x9SNPCyKpFEELfume
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/143.198.216.18/fullchain.pem
    key: /etc/letsencrypt/live/143.198.216.18/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
