debug: false
uuid: a56ebb6a-8652-413f-aaec-c7714ad6b5cf
token_id: pJX2JHXJx9RNV72y
token: RsocpN9bLCD4EORHILP1ChOUp2oerF3Jbgxt0OUjGn1zs6LQzKMNrtjMMlOmObdh
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/159.223.75.122/fullchain.pem
    key: /etc/letsencrypt/live/159.223.75.122/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
