debug: false
uuid: 71a940cd-61c8-467e-bd12-d8229498590a
token_id: OPRmIy3egES5IhB9
token: 551Kz83sOG1IQUafa6UGVLLvSrVNvqNptnAbzRrWPAzLzZNMotBzBXF8v2YtEyYW
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/178.128.58.193/fullchain.pem
    key: /etc/letsencrypt/live/178.128.58.193/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
