debug: false
uuid: 2fe7b1ac-1aad-40a2-b366-3a81a76cd288
token_id: DhbELNCK8uJ5S2ve
token: WfrIdtL8zbDMXB83ys0puhp24AG9Zca3UVMJiirw0Z6MxxfrohZcD9bUYLDdM6Gj
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/157.245.200.175/fullchain.pem
    key: /etc/letsencrypt/live/157.245.200.175/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
