debug: false
uuid: a7d0c33b-9956-43aa-8a17-6c0240da34d8
token_id: Ah5SwsmXRkY1mcPA
token: LJFNoa2aVdctGOIJsM5Dn9in4Qp4DAMOA0m0LBk7PRZsVht5xRHWrdO2vaDIb6nJ
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/68.183.231.79/fullchain.pem
    key: /etc/letsencrypt/live/68.183.231.79/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
