debug: false
uuid: 83b153a9-ccd7-4f87-964e-544a7b3f0313
token_id: ckqvHnXG5PcQs64Z
token: M6Ac8QT9RSKDRGYkWAF7AwGSZRTbChsjlTSAWG7LkMKwBKxzCM5v2lb376KXQhL3
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/165.232.169.137/fullchain.pem
    key: /etc/letsencrypt/live/165.232.169.137/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
