debug: false
uuid: db770702-fe4d-4006-b575-0e26e5ea7c28
token_id: WpOQSmaSH6Ahs7qA
token: FnSVwyIsnVYVkpjQ9N79nR0M0KxP2tukk5h2ciRvZ7F3omHem8SKmis3MttbLwGl
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/157.245.60.76/fullchain.pem
    key: /etc/letsencrypt/live/157.245.60.76/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
