debug: false
uuid: 56e0d8e6-6c63-4dc1-a01a-c411c0f50ebb
token_id: VpROvhlXWUSd2scE
token: NwpOAZoPYZl7fzGUVJs73hotI2wqJVQu8SNLq6HRTgY0Hf2CCFpFTmH4nQI8cLlA
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/159.65.13.72/fullchain.pem
    key: /etc/letsencrypt/live/159.65.13.72/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
