debug: false
uuid: 5e469cc4-1de5-4da3-b4c3-2597719f5573
token_id: PFOXZdJjTasl1qve
token: k8qNuObZ5cYGATs7jiRpswTQYFBeMMp5OXXj7PGqYnrF3LkPwADLZWgkfujjQEip
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/104.248.151.108/fullchain.pem
    key: /etc/letsencrypt/live/104.248.151.108/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
