debug: false
uuid: c1801550-6a4e-4107-9bbf-c67cc25fa979
token_id: SPwB8w0Z4Za09cfS
token: PXG1WJPfzoVVSvE0A9q97jqoWPadBSNMvvDdyJu5ZDwWmGPWIPgUFlMPvbEU29SZ
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/167.71.213.107/fullchain.pem
    key: /etc/letsencrypt/live/167.71.213.107/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
