debug: false
uuid: 9596f688-bde0-435e-b2f8-a3b7e76fbeb5
token_id: sNfHiJKxHKcmc036
token: 1T6v2sKnSKPubbqBnlG205AWv55lPq7CvaYsjePFfPhn6ArJkwZkLe5QftUo5kT5
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/165.232.172.183/fullchain.pem
    key: /etc/letsencrypt/live/165.232.172.183/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
