debug: false
uuid: 37f5ea2e-b614-462a-a9ab-7ecbdae6690c
token_id: ViXRVlC8HCMOAiiW
token: h4HpneWQfMgxG2Cr41bY78C3xMJPogRSv9Qt0Hlxfswc2Lramp3CTUK4gRQzNALr
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/152.42.240.119/fullchain.pem
    key: /etc/letsencrypt/live/152.42.240.119/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
