debug: false
uuid: c045fed3-0a06-4997-aa51-faad629e00fe
token_id: RLZmbBzExzOMFcoe
token: szBlgruonO4Pm3NfGEchzcxrKIMWZlQvCelmgimFEUpZPUUEPCvWlN5OidoTOACF
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/139.59.105.136/fullchain.pem
    key: /etc/letsencrypt/live/139.59.105.136/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
