debug: false
uuid: 1aa21d21-8f39-4d72-b797-be175fb1d9cb
token_id: IiGvq23cKn6l64lp
token: L7l7reO5YgHtuvQyTBltJih8AlQg8gOHAU5jdt4fEMZgkAXlG7pM4bJ2Opx3xotc
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/157.230.244.245/fullchain.pem
    key: /etc/letsencrypt/live/157.230.244.245/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
