debug: false
uuid: b8622693-145e-472a-a968-2f5f83b5e995
token_id: 5JAKvpWOZteLYaCJ
token: souuDunhnvOCl4JKSdJeEfg7LX3KoxITyEKmCs0HRtydztpLIKo4W8OjVRtutXuD
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/159.89.203.48/fullchain.pem
    key: /etc/letsencrypt/live/159.89.203.48/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
