debug: false
uuid: 9647297b-21de-40c5-92d9-19d2dd64d1f9
token_id: 48ue4MQk6VmUNgqV
token: WmTHH6fu1oiRhYMFbdSBY7OBUeosJimZSQAl4vKeUVgmRIc9yjUbvEEYRpi1vYpc
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/157.230.255.168/fullchain.pem
    key: /etc/letsencrypt/live/157.230.255.168/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
