debug: false
uuid: bbd1e237-6fe7-47f0-b06c-ec63bedfa10b
token_id: cO82lelFy6IWerBj
token: Y6J9T7H3RhJiBrI2SNKbxDuB5y7WQ6irIgGrLM9C4vubqMhBidVeIr7hvJXaJOoz
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/128.199.166.29/fullchain.pem
    key: /etc/letsencrypt/live/128.199.166.29/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://152.42.163.24'
